export enum IntentType {
  GET_DAILY_REVENUE = "GET_DAILY_REVENUE",
  GET_CURRENT_SHIFTS = "GET_CURRENT_SHIFTS",
  COMPARE_REVENUE_PERIODS = "COMPARE_REVENUE_PERIODS",
  FOLLOW_UP = "FOLLOW_UP",
  UNKNOWN = "UNKNOWN"
}